/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LMSBook service. Represents a row in the &quot;LSM_LMSBook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.slayer.model.impl.LMSBookModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.slayer.model.impl.LMSBookImpl}.
 * </p>
 *
 * @author Mohammed Ali
 * @see LMSBook
 * @see com.slayer.model.impl.LMSBookImpl
 * @see com.slayer.model.impl.LMSBookModelImpl
 * @generated
 */
public interface LMSBookModel extends BaseModel<LMSBook>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l m s book model instance should use the {@link LMSBook} interface instead.
	 */

	/**
	 * Returns the primary key of this l m s book.
	 *
	 * @return the primary key of this l m s book
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l m s book.
	 *
	 * @param primaryKey the primary key of this l m s book
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the l m s book ID of this l m s book.
	 *
	 * @return the l m s book ID of this l m s book
	 */
	public long getLMSBookId();

	/**
	 * Sets the l m s book ID of this l m s book.
	 *
	 * @param lMSBookId the l m s book ID of this l m s book
	 */
	public void setLMSBookId(long lMSBookId);

	/**
	 * Returns the group ID of this l m s book.
	 *
	 * @return the group ID of this l m s book
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this l m s book.
	 *
	 * @param groupId the group ID of this l m s book
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this l m s book.
	 *
	 * @return the company ID of this l m s book
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this l m s book.
	 *
	 * @param companyId the company ID of this l m s book
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this l m s book.
	 *
	 * @return the user ID of this l m s book
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this l m s book.
	 *
	 * @param userId the user ID of this l m s book
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this l m s book.
	 *
	 * @return the user uuid of this l m s book
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this l m s book.
	 *
	 * @param userUuid the user uuid of this l m s book
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this l m s book.
	 *
	 * @return the user name of this l m s book
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this l m s book.
	 *
	 * @param userName the user name of this l m s book
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this l m s book.
	 *
	 * @return the create date of this l m s book
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this l m s book.
	 *
	 * @param createDate the create date of this l m s book
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this l m s book.
	 *
	 * @return the modified date of this l m s book
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this l m s book.
	 *
	 * @param modifiedDate the modified date of this l m s book
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the book title of this l m s book.
	 *
	 * @return the book title of this l m s book
	 */
	@AutoEscape
	public String getBookTitle();

	/**
	 * Sets the book title of this l m s book.
	 *
	 * @param bookTitle the book title of this l m s book
	 */
	public void setBookTitle(String bookTitle);

	/**
	 * Returns the book author of this l m s book.
	 *
	 * @return the book author of this l m s book
	 */
	@AutoEscape
	public String getBookAuthor();

	/**
	 * Sets the book author of this l m s book.
	 *
	 * @param bookAuthor the book author of this l m s book
	 */
	public void setBookAuthor(String bookAuthor);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LMSBook lmsBook);

	public int hashCode();

	public CacheModel<LMSBook> toCacheModel();

	public LMSBook toEscapedModel();

	public LMSBook toUnescapedModel();

	public String toString();

	public String toXmlString();
}